### ISSUE TITLE
$env:UserName is not case sensitive while URLs are.

### ISSUE THREAD

**Issue by fintanmm** [fintanmm/QuickAccessAlfresco#22]
The username is retrieved from $env:UserName which is not case sensitive so creating a shortcut for the users home will fail because URLs are case sensitive.

**Comment by techdem** [comment]
Looking at the account names in the AD I notice that there isn't a
consistent naming convention in use...

Tested the following alternative on Ben's machine (Ma*****) and the results
is also lowercase (ma*****):

[System.Security.Principal.WindowsIdentity]::GetCurrent().Name

Tudor Chiribes


*LinkedIn :* https://ie.linkedin.com/in/tud0r
*Website  :* http://tudorthetechie.com
